import { app } from 'electron';
import { type SQLJsDatabase as DrizzleDatabase, drizzle } from 'drizzle-orm/sql-js';
import { migrate } from 'drizzle-orm/sql-js/migrator';
import * as fs from 'fs';
import * as path from 'path';
import logger from '@/lib/utils/logger';
import * as schema from './schema';

// Dynamic require for sql.js to avoid bundling issues
// eslint-disable-next-line @typescript-eslint/no-require-imports
const initSqlJs = require('sql.js') as typeof import('sql.js').default;
type SqlJsDatabase = import('sql.js').Database;

let db: DrizzleDatabase<typeof schema> | null = null;
let sqlite: SqlJsDatabase | null = null;
let dbPath: string = '';

function getDbPath(): string {
  const userDataPath = app.getPath('userData');
  return path.join(userDataPath, 'xplane-data.db');
}

/**
 * Check if a table exists in the database
 */
function tableExists(sqlite: SqlJsDatabase, tableName: string): boolean {
  const result = sqlite.exec(
    `SELECT name FROM sqlite_master WHERE type='table' AND name='${tableName}';`
  );
  return result.length > 0 && result[0].values.length > 0;
}

/**
 * TEMPORARY: Remove after v1.1+ when all users have migrated.
 *
 * Handles databases created before Drizzle migrations were introduced.
 * If tables exist but __drizzle_migrations doesn't, mark init migration as done.
 * This prevents the init migration from trying to CREATE tables that already exist.
 */
function handleLegacyDatabase(sqlite: SqlJsDatabase): void {
  const hasTables = tableExists(sqlite, 'airports');
  const hasMigrationsTable = tableExists(sqlite, '__drizzle_migrations');

  if (hasTables && !hasMigrationsTable) {
    logger.data.info('Legacy database detected, marking init migration as complete');

    // Create the migrations table
    sqlite.run(`
      CREATE TABLE IF NOT EXISTS __drizzle_migrations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        hash TEXT NOT NULL,
        created_at INTEGER
      );
    `);

    // Mark the init migration (0000_init) as complete
    // Hash is generated by drizzle-kit - we need to match what's in the journal
    const journalPath = path.join(app.getAppPath(), 'drizzle/meta/_journal.json');
    try {
      const journal = JSON.parse(fs.readFileSync(journalPath, 'utf-8'));
      const initMigration = journal.entries[0];
      if (initMigration) {
        sqlite.run(
          `INSERT INTO __drizzle_migrations (hash, created_at) VALUES ('${initMigration.tag}', ${Date.now()});`
        );
        logger.data.info(`Marked migration ${initMigration.tag} as complete`);
      }
    } catch (error) {
      logger.data.warn('Could not read migration journal, migrations may re-run:', error);
    }
  }
}

export async function initDb(): Promise<DrizzleDatabase<typeof schema>> {
  if (db) return db;

  dbPath = getDbPath();
  logger.data.info(`Database initializing: ${dbPath}`);

  const SQL = await initSqlJs();

  // Load existing database or create new one
  let data: Buffer | undefined;
  if (fs.existsSync(dbPath)) {
    data = fs.readFileSync(dbPath);
  }

  sqlite = new SQL.Database(data);
  db = drizzle(sqlite, { schema });

  // Handle legacy databases before running migrations
  handleLegacyDatabase(sqlite);

  // Run Drizzle migrations
  const migrationsFolder = path.join(app.getAppPath(), 'drizzle');
  migrate(db, { migrationsFolder });
  logger.data.info(`Database migrations complete`);

  logger.data.info(`Database initialized: ${dbPath}`);

  return db;
}

export function getDb(): DrizzleDatabase<typeof schema> {
  if (!db) {
    throw new Error('Database not initialized. Call initDb() first.');
  }
  return db;
}

export function saveDb(): void {
  if (!sqlite || !dbPath) return;

  const data = sqlite.export();
  const buffer = Buffer.from(data);

  // Ensure directory exists
  const dir = path.dirname(dbPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(dbPath, buffer);
  logger.data.info('Database saved to disk');
}

export function closeDb(): void {
  if (sqlite) {
    saveDb();
    sqlite.close();
    sqlite = null;
    db = null;
  }
}

export * from './schema';
